id: A8C881247
title: A Synopsis of Guru Padmasambhava’s Life
type: translation
pechas:
- IAA43A238
- I36D5D55C
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:27:57.487365
  last_modified_at: 2023-01-04 11:27:57.487381
  collections:
  - Alak Zenkar Pema Ngödrup Rolwe Dorje
  - Works of Tibetan Masters
alignment_to_base:
  IAA43A238/5458: F33E
  I36D5D55C/C682: F33E
